import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import PaddleLoader from "../components/PaddleLoader";
import styles from "../styles/Home.module.css";

export default function Home() {
  const options = {
    method: "POST",
    url: "https://stoplight.io/mocks/paddle/api-reference/30744709/2.0/product/generate_pay_link",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Prefer: "code=200",
    },
    data: {
      vendor_id: 11032,
      vendor_auth_code: "907206cf7dd48881a4733adaf63472271ac1be596ecb8d92de",
      product_id: 46295,
      // title: "Custom Product",
      // webhook_url:
      //   "https://dirty-chairs-wear-116-206-89-13.loca.lt/api/paddlewebhook",
      // prices: ["USD:19.99"],
      // custom_message: "This is a good product",
      // image_url: "https://themefisher.com/images/logo/logo.svg",
      // return_url: "/",
      // quantity_variable: 0,
      // quantity: 1,
      // marketing_consent: 1,
      // customer_email: "themefisher.dev@gmail.com",
      // customer_country: "BD",
      // customer_postcode: "1207",
      // is_recoverable: 0,
    },
  };

  const [customURL, setCustomURL] = useState("");

  useEffect(() => {
    const handlePaymentURL = async () => {
      const getURL = await axios.request(options);
      setCustomURL(getURL.data.response.url);
    };
    handlePaymentURL();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  console.log(customURL);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaddleLoader />
      <main className={styles.main}>
        <button
          style={{ marginBottom: "40px" }}
          onClick={() =>
            Paddle.Checkout.open({
              override: customURL,
            })
          }
        >
          Purchace Custom Product
        </button>
        <button
          onClick={() => {
            Paddle.Checkout.open({ product: 46295 });
          }}
        >
          Purchace From Paddle
        </button>
      </main>
    </div>
  );
}
